In [1]:
%pip install sqlalchemy psycopg2-binary python-dotenv

Requirement already satisfied: sqlalchemy in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.13)
Requirement already satisfied: python-dotenv in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.3)
Requirement already satisfied: greenlet>=1 in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

# Loading data with SQL query into a DataFrame

In [3]:
load_dotenv()
engine = create_engine(os.getenv("SUPABASE_DB_URL"))

query = "SELECT * FROM weather_logs ORDER BY timestamp ASC;"
df = pd.read_sql(query, con=engine)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m,created_at
0,2026-09-10 00:00:00+00:00,20.017500,80.0,0.0,997.721802,0.0,21.599998,308.0,19.117563,100.0,37.079998,2026-09-10 18:59:15.051899+00:00
1,2026-09-10 01:00:00+00:00,19.367500,74.0,0.0,998.480835,0.0,23.759998,316.0,17.427710,99.0,44.279999,2026-09-10 18:59:15.051899+00:00
2,2026-09-10 02:00:00+00:00,18.117500,73.0,0.0,998.225281,0.0,19.440001,318.0,16.302025,100.0,43.199997,2026-09-10 18:59:15.051899+00:00
3,2026-09-10 03:00:00+00:00,17.817501,77.0,0.0,998.901550,0.0,18.000000,312.0,16.397026,46.0,33.119999,2026-09-10 18:59:15.051899+00:00
4,2026-09-10 04:00:00+00:00,17.967501,75.0,0.0,999.500305,0.0,17.280001,303.0,16.560665,88.0,33.119999,2026-09-10 18:59:15.051899+00:00

In [4]:
df.shape

(110, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             110 non-null    datetime64[us, UTC]
 1   temperature_2m        110 non-null    float64
 2   relative_humidity_2m  110 non-null    float64
 3   rain                  110 non-null    float64
 4   surface_pressure      110 non-null    float64
 5   precipitation         110 non-null    float64
 6   wind_speed_10m        110 non-null    float64
 7   wind_direction_10m    110 non-null    float64
 8   apparent_temperature  110 non-null    float64
 9   cloud_cover           110 non-null    float64
 10  wind_gusts_10m        110 non-null    float64
 11  created_at            110 non-null    datetime64[us, UTC]
dtypes: datetime64[us, UTC](2), float64(10)
memory usage: 10.4 KB

In [6]:
df.describe()

,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,17.864319,61.745455,0.101818,1005.572488,0.101818,8.597454,238.590909,16.628834,71.909091,18.575999
std,3.281826,23.442076,0.467078,2.678596,0.467078,4.463151,115.927793,3.322098,40.141389,7.719014
min,11.517500,1.000000,0.000000,997.721802,0.000000,0.720000,7.000000,9.637831,0.000000,5.400000
25%,15.817500,47.000000,0.000000,1003.880447,0.000000,5.760000,130.250000,14.293040,43.000000,13.049999
50%,18.092501,65.000000,0.000000,1006.066864,0.000000,7.559999,302.500000,16.947893,99.000000,17.820000
75%,20.267500,83.000000,0.000000,1007.412262,0.000000,11.069999,326.750000,19.183754,100.000000,22.319998
max,24.367500,92.000000,3.500000,1009.324890,3.500000,23.759998,360.000000,23.069096,100.000000,44.279999

In [7]:
df.isnull().sum()

timestamp               0
temperature_2m          0
relative_humidity_2m    0
rain                    0
surface_pressure        0
precipitation           0
wind_speed_10m          0
wind_direction_10m      0
apparent_temperature    0
cloud_cover             0
wind_gusts_10m          0
created_at              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.nunique()

timestamp               110
temperature_2m           88
relative_humidity_2m     53
rain                      9
surface_pressure        110
precipitation             9
wind_speed_10m           43
wind_direction_10m       85
apparent_temperature    110
cloud_cover              30
wind_gusts_10m           56
created_at               27
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)