In [1]:
%pip install sqlalchemy psycopg2-binary python-dotenv

Requirement already satisfied: sqlalchemy in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.13)
Requirement already satisfied: python-dotenv in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.3)
Requirement already satisfied: greenlet>=1 in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\heged\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

# Loading data with SQL query into a DataFrame

In [2]:
load_dotenv()
engine = create_engine(os.getenv("SUPABASE_DB_URL"))

query = "SELECT * FROM weather_logs ORDER BY timestamp ASC;"
df = pd.read_sql(query, con=engine)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m,created_at
0,2026-05-01 00:00:00+00:00,6.65,40.799706,0.0,1013.241638,0.0,2.189795,9.462248,3.467545,8.0,5.400000,2026-09-14 19:20:16.466953+00:00
1,2026-05-01 01:00:00+00:00,4.85,45.861950,0.0,1013.148132,0.0,3.931259,15.945477,1.402924,2.0,6.480000,2026-09-14 19:20:16.466953+00:00
2,2026-05-01 02:00:00+00:00,4.50,48.447136,0.0,1013.228455,0.0,5.182625,20.323217,0.912885,0.0,9.720000,2026-09-14 19:20:16.466953+00:00
3,2026-05-01 03:00:00+00:00,4.10,53.936569,0.0,1013.109009,0.0,6.122646,24.304548,0.492876,0.0,11.520000,2026-09-14 19:20:16.466953+00:00
4,2026-05-01 04:00:00+00:00,4.10,58.566833,0.0,1013.109009,0.0,6.952754,21.250580,0.503658,0.0,12.599999,2026-09-14 19:20:16.466953+00:00

In [3]:
df.shape

(3467, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3467 entries, 0 to 3466
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             3467 non-null   datetime64[us, UTC]
 1   temperature_2m        3467 non-null   float64
 2   relative_humidity_2m  3467 non-null   float64
 3   rain                  3467 non-null   float64
 4   surface_pressure      3467 non-null   float64
 5   precipitation         3467 non-null   float64
 6   wind_speed_10m        3467 non-null   float64
 7   wind_direction_10m    3467 non-null   float64
 8   apparent_temperature  3467 non-null   float64
 9   cloud_cover           3467 non-null   float64
 10  wind_gusts_10m        3467 non-null   float64
 11  created_at            3467 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](2), float64(10)
memory usage: 325.2 KB

In [5]:
df.describe()

,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
count,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000,3467.000000
mean,23.090324,47.040296,0.035102,1002.749865,0.035102,8.992514,211.644887,22.118983,38.073551,23.164291
std,6.182211,19.475602,0.208350,4.904850,0.208350,4.647495,111.039265,6.754434,38.548185,10.563702
min,4.100000,1.000000,0.000000,986.185486,0.000000,0.000000,0.868040,0.492876,0.000000,1.440000
25%,18.799999,31.171610,0.000000,1000.060150,0.000000,5.483356,116.564987,17.562131,2.000000,15.119999
50%,22.900000,44.206749,0.000000,1003.045715,0.000000,8.311245,224.999893,21.893370,22.000000,21.599998
75%,27.150000,60.012899,0.000000,1005.969055,0.000000,12.093535,314.000000,26.511002,79.000000,30.239998
max,40.500000,98.689995,3.500000,1014.025330,3.500000,27.719999,360.000000,41.391159,100.000000,65.879997

In [6]:
df.isnull().sum()

timestamp               0
temperature_2m          0
relative_humidity_2m    0
rain                    0
surface_pressure        0
precipitation           0
wind_speed_10m          0
wind_direction_10m      0
apparent_temperature    0
cloud_cover             0
wind_gusts_10m          0
created_at              0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

timestamp               3467
temperature_2m           776
relative_humidity_2m    3177
rain                      26
surface_pressure        3376
precipitation             26
wind_speed_10m          1747
wind_direction_10m      2483
apparent_temperature    3467
cloud_cover              101
wind_gusts_10m           153
created_at                86
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['timestamp', 'temperature_2m', 'relative_humidity_2m', 'rain',
       'surface_pressure', 'precipitation', 'wind_speed_10m',
       'wind_direction_10m', 'apparent_temperature', 'cloud_cover',
       'wind_gusts_10m', 'created_at'],
      dtype='str')