In [6]:
import os
import pandas as pd
from sqlalchemy import create_engine
import scipy as sp
from scipy import stats

from dotenv import load_dotenv

In [5]:
load_dotenv()
engine = create_engine(os.getenv("SUPABASE_DB_URL"))

query = "SELECT * FROM weather_logs_cleaned ORDER BY timestamp ASC;"
df = pd.read_sql(query, con=engine)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
0,2026-09-10 00:00,20.02,80.0,0.0,997.72,0.0,21.60,308.0,19.12,100.0,37.08
1,2026-09-10 01:00,19.37,74.0,0.0,998.48,0.0,23.76,316.0,17.43,99.0,44.28
2,2026-09-10 02:00,18.12,73.0,0.0,998.23,0.0,19.44,318.0,16.30,100.0,43.20
3,2026-09-10 03:00,17.82,77.0,0.0,998.90,0.0,18.00,312.0,16.40,46.0,33.12
4,2026-09-10 04:00,17.97,75.0,0.0,999.50,0.0,17.28,303.0,16.56,88.0,33.12

In [10]:
df.dtypes

timestamp                   str
temperature_2m          float64
relative_humidity_2m    float64
rain                    float64
surface_pressure        float64
precipitation           float64
wind_speed_10m          float64
wind_direction_10m      float64
apparent_temperature    float64
cloud_cover             float64
wind_gusts_10m          float64
dtype: object

#  Descriptive statistics

In [13]:
df.describe()

,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,18.747632,67.763158,0.263158,1002.562895,0.263158,11.425263,252.921053,17.843421,93.684211,23.040000
std,1.934142,13.725955,0.763853,1.993603,0.763853,4.683878,124.749995,1.548587,18.331932,8.630265
min,15.620000,48.000000,0.000000,997.720000,0.000000,6.120000,16.000000,15.650000,14.000000,11.160000
25%,17.670000,57.250000,0.000000,1002.112500,0.000000,8.370000,296.250000,16.437500,99.000000,16.740000
50%,18.220000,64.500000,0.000000,1003.220000,0.000000,9.540000,312.500000,17.310000,100.000000,19.800000
75%,20.207500,76.500000,0.000000,1003.912500,0.000000,14.400000,326.500000,19.110000,100.000000,29.520000
max,22.070000,92.000000,3.500000,1004.770000,3.500000,23.760000,357.000000,20.390000,100.000000,44.280000

In [7]:
stat,p= stats.shapiro(df["temperature_2m"])
print("Statistic:", stat)
print("p-value:", p)

Statistic: 0.947476595845895
p-value: 0.07353967332393732

In [11]:
r,p= stats.pearsonr(df["temperature_2m"],df["relative_humidity_2m"])
print(f"r = {r:.3f}")
print(f"p-value = {p:.5f}")

r = -0.861
p-value = 0.00000